[package]
name = "clak-gui"
version = "0.2.8"
edition = "2021"

[dependencies]
clak-engine = { path = "../engine" }
slint = { version = "1.9", default-features = false, features = ["backend-winit", "renderer-femtovg", "compat-1-2", "accessibility"] }
serde = { version = "1.0", features = ["derive"] }
toml = "0.8"

[build-dependencies]
slint-build = "1.9"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true
